service: aws-customers-api
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
plugins:
  - serverless-offline
functions:
  listCustomers:
    handler: handler.listCustomers
    events:
      - http:
          path: customers
          method: get
  getCustomerById:
    handler: handler.getCustomerById
    events:
      - http:
          path: customers/{id}
          method: get
