service: aws-customers-api
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
functions:
  listCustomers:
    handler: handler.listCustomers
    events:
      - http:
          path: customers
          method: get
